# Generated by Django 4.1.1 on 2023-06-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('steps_to_recreate', models.TextField()),
                ('opened_on', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('time_tracker', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('not_started', 'Not Started'), ('closed', 'Closed')], default='not_started', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bug.project')),
            ],
        ),
    ]
